# Generated by Django 4.0.3 on 2022-05-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('crab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('checkout', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.AlterModelOptions(
            name='moderator',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
        migrations.AddField(
            model_name='moderator',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moderator',
            name='profile_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[600, 600], upload_to='moderators/img/'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crab.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.product')),
            ],
            options={
                'verbose_name': 'Товар на Заказ',
                'verbose_name_plural': 'Товары на Заказ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crab.moderator'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crab.ordertype'),
        ),
    ]
