# Generated by Django 4.0.3 on 2022-05-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('crab', '0003_order_account_alter_order_address_alter_order_fio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('reader_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reader_account', to='control.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sender_account', to='control.account')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задании',
            },
        ),
    ]
