# Generated by Django 4.0.3 on 2022-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crab', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.BooleanField(default=False),
        ),
    ]
