# Generated by Django 4.0.3 on 2022-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crab', '0006_rename_task_task_istask'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drop',
            field=models.BooleanField(default=False),
        ),
    ]
