# Generated by Django 4.0.3 on 2022-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crab', '0007_order_drop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_checkout',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='date_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
