# Generated by Django 4.0.3 on 2022-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crab', '0009_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
