# Generated by Django 4.0.3 on 2022-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_office_remove_product_discount_blog_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.AddField(
            model_name='office',
            name='description_uz',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
