# Generated by Django 4.0.3 on 2022-04-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_description_blog_description_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disctrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Городы',
            },
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Region',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='disctrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region'),
        ),
    ]
