# Generated by Django 4.0.3 on 2022-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_disctrict_rename_country_region_delete_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='content_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='content_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
