# Generated by Django 4.0.3 on 2022-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_slider_content_ru_slider_content_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
