# Generated by Django 4.0.3 on 2022-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_slider_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
