# Generated by Django 4.0.3 on 2022-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_slider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
