# Generated by Django 4.0.3 on 2022-04-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_office_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='title_uz',
        ),
    ]
