# Generated by Django 4.0.3 on 2022-04-14 10:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_title_ru_discount_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_full',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[600, 600], upload_to='blogs/'),
        ),
    ]
