# Generated by Django 4.0.3 on 2022-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_order_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertypes',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
