# Generated by Django 4.0.3 on 2022-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_ordertypes_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_fk',
            new_name='discount',
        ),
    ]
