# Generated by Django 4.0.3 on 2022-04-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_officeaddress_officeemail_officephone_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='disctrict',
            name='region',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='OfficeAddress',
        ),
        migrations.DeleteModel(
            name='OfficeEmail',
        ),
        migrations.DeleteModel(
            name='OfficePhone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordertypes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Disctrict',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderTypes',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
