# Generated by Django 4.0.3 on 2022-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='office',
            name='title_uz',
        ),
        migrations.AlterField(
            model_name='office',
            name='currency',
            field=models.CharField(blank=True, default='UZS', max_length=255, null=True),
        ),
    ]
