# Generated by Django 4.0.3 on 2022-04-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_contact_remove_office_title_uz_alter_office_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
