# Generated by Django 4.0.3 on 2022-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_office_email_alter_office_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeaddress',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
