# Generated by Django 4.0.3 on 2022-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_lang',
            field=models.CharField(blank=True, choices=[('ru', 'Русские'), ('uz', "O'zbekcha")], max_length=5, null=True),
        ),
    ]
