# Generated by Django 4.0.3 on 2022-04-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_account_telegram_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='category_imgs',
            field=models.BooleanField(default=False),
        ),
    ]
