# Generated by Django 4.0.3 on 2022-04-29 04:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_office_category_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[600, 600], upload_to='control/categories/'),
        ),
    ]
