# Generated by Django 4.0.3 on 2022-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='main_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('moderator', 'Moderator-Admin'), ('admin', 'Controller'), ('superadmin', 'SuperAdmin'), ('dev', 'Developer')], max_length=255),
        ),
    ]
