# Generated by Django 4.0.3 on 2022-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_office_main_color_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('dev', 'Developer')], max_length=255),
        ),
    ]
