# Generated by Django 4.0.3 on 2022-05-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderTypes',
        ),
    ]
