# Generated by Django 4.0.3 on 2022-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
