# Generated by Django 4.0.3 on 2022-05-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
