# Generated by Django 4.0.3 on 2022-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_account_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('developer', 'Developer')], default='client', max_length=255),
        ),
    ]
